# Generated by Django 2.1.1 on 2018-09-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True)),
                ('discount', models.FloatField(blank=True)),
                ('pictures', models.CharField(max_length=800)),
                ('weight', models.IntegerField(default=1)),
                ('introduction', models.TextField(blank=True)),
            ],
        ),
    ]
