# Generated by Django 2.1.1 on 2018-09-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcxt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='discount',
            field=models.FloatField(default=1.0),
        ),
    ]
