# Generated by Django 2.1.1 on 2018-09-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcxt', '0003_auto_20180913_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
