# Generated by Django 2.1.1 on 2018-09-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcxt', '0006_remove_dish_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img_info',
            field=models.CharField(blank=True, max_length=420, null=True),
        ),
    ]
