# Generated by Django 2.1.1 on 2018-09-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcxt', '0007_auto_20180918_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img_url',
            field=models.ImageField(upload_to='img/%Y/%m/%d'),
        ),
    ]
